package com.example.learninglibraries.domain.database.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

@Entity(
    foreignKeys = [ForeignKey(
        entity = RoomGithubUser::class,
        parentColumns = ["id"],
        childColumns = ["owner"],
        onDelete = ForeignKey.CASCADE
    )]
)
data class RoomGithubRepository(
    @PrimaryKey var id: Long?,
    @ColumnInfo(name = "allow_forking") val allowForking: Boolean?,
    @ColumnInfo(name = "archive_url") val archiveUrl: String?,
    @ColumnInfo(name = "archived") val archived: Boolean?,
    @ColumnInfo(name = "assignees_url") val assigneesUrl: String?,
    @ColumnInfo(name = "blobs_url") val blobsUrl: String?,
    @ColumnInfo(name = "branches_url") val branchesUrl: String?,
    @ColumnInfo(name = "clone_url") val cloneUrl: String?,
    @ColumnInfo(name = "collaborators_url") val collaboratorsUrl: String?,
    @ColumnInfo(name = "comments_url") val commentsUrl: String?,
    @ColumnInfo(name = "commits_url") val commitsUrl: String?,
    @ColumnInfo(name = "compare_url") val compareUrl: String?,
    @ColumnInfo(name = "contents_url") val contentsUrl: String?,
    @ColumnInfo(name = "contributors_url") val contributorsUrl: String?,
    @ColumnInfo(name = "created_at") val createdAt: String?,
    @ColumnInfo(name = "default_branch") val defaultBranch: String?,
    @ColumnInfo(name = "deployments_url") val deploymentsUrl: String?,
    @ColumnInfo(name = "description") val description: String?,
    @ColumnInfo(name = "disabled") val disabled: Boolean?,
    @ColumnInfo(name = "downloads_url") val downloadsUrl: String?,
    @ColumnInfo(name = "events_url") val eventsUrl: String?,
    @ColumnInfo(name = "fork") val fork: Boolean?,
    @ColumnInfo(name = "forks") val forks: Int?,
    @ColumnInfo(name = "forks_count") var forksCount: Int?,
    @ColumnInfo(name = "forks_url") val forksUrl: String?,
    @ColumnInfo(name = "full_name") var fullName: String?,
    @ColumnInfo(name = "git_commits_url") val gitCommitsUrl: String?,
    @ColumnInfo(name = "gitRefs_url") val gitRefsUrl: String?,
    @ColumnInfo(name = "git_tags_url") val gitTagsUrl: String?,
    @ColumnInfo(name = "git_url") val gitUrl: String?,
    @ColumnInfo(name = "has_downloads") val hasDownloads: Boolean?,
    @ColumnInfo(name = "has_issues") val hasIssues: Boolean?,
    @ColumnInfo(name = "has_pages") val hasPages: Boolean?,
    @ColumnInfo(name = "has_projects") val hasProjects: Boolean?,
    @ColumnInfo(name = "has_wiki") val hasWiki: Boolean?,
    @ColumnInfo(name = "homepage") val homepage: String?,
    @ColumnInfo(name = "hooks_url") val hooksUrl: String?,
    @ColumnInfo(name = "html_url") val htmlUrl: String?,
    @ColumnInfo(name = "is_template") val isTemplate: Boolean?,
    @ColumnInfo(name = "issue_comment_url") val issueCommentUrl: String?,
    @ColumnInfo(name = "issue_events_url") val issueEventsUrl: String?,
    @ColumnInfo(name = "issues_url") val issuesUrl: String?,
    @ColumnInfo(name = "keys_url") val keysUrl: String?,
    @ColumnInfo(name = "labels_url") val labelsUrl: String?,
    @ColumnInfo(name = "language") val language: String?,
    @ColumnInfo(name = "languages_url") val languagesUrl: String?,
    @ColumnInfo(name = "merges_url") val mergesUrl: String?,
    @ColumnInfo(name = "milestones_url") val milestonesUrl: String?,
    @ColumnInfo(name = "mirror_url") val mirrorUrl: String?,
    @ColumnInfo(name = "name") val name: String?,
    @ColumnInfo(name = "node_id") val nodeId: String?,
    @ColumnInfo(name = "notifications_url") val notificationsUrl: String?,
    @ColumnInfo(name = "open_issues") val openIssues: Int?,
    @ColumnInfo(name = "open_issues_count") val openIssuesCount: Int?,
    @ColumnInfo(name = "owner") var owner: Long?,
    @ColumnInfo(name = "pulls_url") val pullsUrl: String?,
    @ColumnInfo(name = "pushed_at") val pushedAt: String?,
    @ColumnInfo(name = "releases_url") val releasesUrl: String?,
    @ColumnInfo(name = "size") val size: Int?,
    @ColumnInfo(name = "ssh_url") val sshUrl: String?,
    @ColumnInfo(name = "stargazers_count") val stargazersCount: Int?,
    @ColumnInfo(name = "stargazers_url") val stargazersUrl: String?,
    @ColumnInfo(name = "statuses_url") val statusesUrl: String?,
    @ColumnInfo(name = "subscribers_url") val subscribersUrl: String?,
    @ColumnInfo(name = "subscription_url") val subscriptionUrl: String?,
    @ColumnInfo(name = "svn_url") val svnUrl: String?,
    @ColumnInfo(name = "tags_url") val tagsUrl: String?,
    @ColumnInfo(name = "teams_url") val teamsUrl: String?,
    @ColumnInfo(name = "trees_url") val treesUrl: String?,
    @ColumnInfo(name = "updated_at") val updatedAt: String?,
    @ColumnInfo(name = "url") val url: String?,
    @ColumnInfo(name = "visibility") val visibility: String?,
    @ColumnInfo(name = "watchers") val watchers: Int?,
    @ColumnInfo(name = "watchers_count") val watchersCount: Int?
)